### ISSUE TITLE
Fetch PMCID option missing from item menu

### ISSUE THREAD

**Issue by enozkan** [retorquere/zotero-pmcid-fetcher#1]
Upon right-clicking an item in 0.0.8, Fetch PMCID option no longer shows in the menu. Installing 0.0.6 brings back the function.

Debug logs here, although I am not sure they are useful in this case:
https://file.io/a56f1VFjHs6f
https://file.io/dLAQPS7kvBzc

Also, typo: "PCMID Debug logs" should be "PMCID Debug logs".

**Comment by retorquere** [comment]
Both fixed in 0.0.9. A regular update from the gear menu in the addons screen should do it.

**Comment by enozkan** [comment]
The update fixed the issue. Thank you.
