### ISSUE TITLE
Can't import install.rdf

### ISSUE THREAD

**Issue by abarnett313** [retorquere/zotero-pmcid-fetcher#10]
Recently wiped my Mac and am reinstalling things, and when I try to install the latest version of the plugin by importing install.rdf, I get the error message that the file is not in a supported format. Using Zotero v6.0.30 for Mac. Tried the second-most-recent version of the plugin and had the same issue.

**Comment by retorquere** [comment]
That's not how you install the plugin, you must install the xpi from the addons screen under tools.

**Comment by abarnett313** [comment]
Ah. Sorry about that. I figured it out last time, so not sure why I didn't
this time. Thanks!
