### ISSUE TITLE
Fetching tags should default to false

### ISSUE THREAD

**Issue by mhucka** [retorquere/zotero-pmcid-fetcher#11]
I appreciate the time and effort it took to create this useful plugin, and I am happy it exists, but … the documentation does not mention (nor does the plugin's name even suggest) that by default, it will not _only_ get PMCID's, but _also_ all the PMC/Medline tags for the items. This caught me unaware today and I inadvertently ended up adding _hundreds_ of unwanted tags to my Zotero library as a result of running the plugin on a batch of items in my library. Only by searching the closed issues in this repo did I discover issue #9, wherein there's an explanation of how to set a hidden preference to turn off this behavior.

I kindly request that the sense of the flag be reversed: the behavior should be off/`false` by default, and users should turn it on by setting the key `extensions.zotero.pmcid.tags` to `true`. This will make the out-of-the-box behavior more in line with the name and description of the plugin and prevent accidents.

**Comment by retorquere** [comment]
This version will ask the first time it tries to retrieve tags. Is that an acceptable solution?

**Comment by mhucka** [comment]
Thanks for your frighteningly fast response. That sounds like a reasonable approach. However – and I don't mean to be ungracious – IMHO it would also be good to mention in the docs or the README how users can change the setting after they make their choice the first time. I think it's probably not very obvious to most users.

**Comment by retorquere** [comment]
Done!
