### ISSUE TITLE
Zotero 7 support

### ISSUE THREAD

**Issue by zhang-ziyang** [retorquere/zotero-pmcid-fetcher#14]
HI!  Big fan of this add-on.  It looks like somehow the context-menu no longer shows "Fetch PMCID" in Zotero 7.  The add-on can be successfully installed though - wondering if there are any tweaks?  Thanks!

**Comment by alexreg** [comment]
I was wondering about the same thing.

@retorquere I might be able to look into this. Would you take a PR?

**Comment by retorquere** [comment]
Yes, absolutely.

**Comment by pmendes** [comment]
This would be very welcome to many people, Hope the open PR can be integrated soon...

**Comment by retorquere** [comment]
Man I totally missed this, sorry!

**Comment by pmendes** [comment]
Works great, thanks!

**Comment by zhang-ziyang** [comment]
Thank you! My zotero is on steroid again!

**Comment by alexreg** [comment]
@retorquere Happy to make a new release now?

**Comment by retorquere** [comment]
release is running now
