### ISSUE TITLE
PMCID: Could not fetch PCMID

### ISSUE THREAD

**Issue by joshvest** [retorquere/zotero-pmcid-fetcher#2]
Getting the attached error. PMCID: Could not fetch.....Unexpected response from API. The journal is definitely indexed.

Zotero 5.0.93
Mac 10.15.7
Fetcher 0.0.11

![Screen Shot 2020-11-19 at 6 58 52 AM](https://user-images.githubusercontent.com/45064250/99663540-c82d2580-2a34-11eb-9d9e-7773d17ff278.png)

**Comment by retorquere** [comment]
When I plug [that URL](
https://www.ncbi.nlm.nih.gov/pmc/utils/idconv/v1.0/?tool=zotero&email=email%3Demiliano.heyns%40iris-advies.com&ids=10%2Ff6bmst&format=json&idtype=doi&versions=no) in a browser, I get

```
{
 "status": "error",
 "message": "ID%20type%20of%20%2710%2Ff6bmst%27%20is%20unknown",
 "responseDate": "2020-11-19 07:27:49",
 "request": "tool=zotero;email=email%3Demiliano.heyns%40iris-advies.com;ids=10%2Ff6bmst;format=json;idtype=doi;versions=no"
}
```

and this is not the expected response.

The message says "ID type of '10/f6bmst' is unknown", but I don't know why they throw an error instead of returning zero results, and I don't know why they're encoding the response this way (URL-encoded JSON).

**Comment by joshvest** [comment]
Should have added that the result isn't for a "no citation found" these are coming back for articles that are indexed.

**Comment by retorquere** [comment]
I understand that, but I'm calling [the nih API](https://www.ncbi.nlm.nih.gov/pmc/tools/id-converter-api/), and as far as I can tell, https://www.ncbi.nlm.nih.gov/pmc/utils/idconv/v1.0/?tool=zotero&email=email%3Demiliano.heyns%40iris-advies.com&ids=10%2Ff6bmst&format=json&idtype=doi&versions=no is a valid API url requesting to resolve the DOI `10/f6bmst`, to which they respond with an error. I can't do anything about that. I'm not putting in a wrong request, and I'm not misinterpreting the answer. Their answer to resolve that entry is just literally 

```
{
 "status": "error",
 "message": "ID%20type%20of%20%2710%2Ff6bmst%27%20is%20unknown",
 "responseDate": "2020-11-19 07:27:49",
 "request": "tool=zotero;email=email%3Demiliano.heyns%40iris-advies.com;ids=10%2Ff6bmst;format=json;idtype=doi;versions=no"
}
```

So it's *them* saying that 

> ID type of '10/f6bmst' is unknown

even though I explicitly tell them, as per their spec, that the ID type is `doi`.

**Comment by joshvest** [comment]
I don't know what it is about there ends. 
https://www.ncbi.nlm.nih.gov/pmc/pmctopmid/
searched this DOI: 10.1097/mlr.0000000000001049. no result.
But in the second screen shot it does have a PMID AND using the "standard" pubmed search with the DOI gets the result.

![Screen Shot 2020-11-20 at 7 09 13 AM](https://user-images.githubusercontent.com/45064250/99798680-6980ae00-2aff-11eb-84fa-7fd795a8cdd3.png)
![Screen Shot 2020-11-20 at 7 09 44 AM](https://user-images.githubusercontent.com/45064250/99798683-6c7b9e80-2aff-11eb-8f15-640f8fa64b90.png)

**Comment by retorquere** [comment]
I'm afraid that means something is broken on their end.

**Comment by joshvest** [comment]
sigh...fed gov tech support....i will see if i can dig up a email for them.

**Comment by retorquere** [comment]
I've sent them an email. We'll have to see how they respond.

**Comment by bwiernik** [comment]
It looks like their API doesn't properly handle shortDOIs (form `10/xxx`). @retorquere perhaps you might want to reject them as well and only accept proper DOIs (form `10.dddd/xxx`).

**Comment by joshvest** [comment]
Will it return a PMID if there is no PMCID? I seem to be getting no response unless there is both....

**Comment by retorquere** [comment]
I can resolve short dois myself right? The doi manager plugin does it.

**Comment by bwiernik** [comment]
Yeah, you could resolve them, or retrieve the corresponding full DOI using the shortDOI API like the "long" function in DOI Manager.

**Comment by retorquere** [comment]
> Will it return a PMID if there is no PMCID? I seem to be getting no response unless there is both....

If I get back either or both, I add them, but that's entirely dependent on their API not being broken.

> or retrieve the corresponding full DOI using the shortDOI API like the "long" function in DOI Manager.

I can't find the function to call in zoteroshortdoi.js

**Comment by bwiernik** [comment]
See 
https://github.com/bwiernik/zotero-shortdoi/blob/6d52a6ce323c24982a67010e3dcb52730cc911d6/chrome/content/scripts/zoteroshortdoi.js#L185

for the DOI URL to generate, then here
https://github.com/bwiernik/zotero-shortdoi/blob/6d52a6ce323c24982a67010e3dcb52730cc911d6/chrome/content/scripts/zoteroshortdoi.js#L330

for how to retrieve a long DOI from a shortDOI response.

**Comment by retorquere** [comment]
Best to leave shortdoi resolution to the shortdoi plugin maybe. Shortdois are not long for this world it appears, so maybe not worth duplicating.
