### ISSUE TITLE
Zotero - PMID/PMCID

### ISSUE THREAD

**Issue by vicdsim** [retorquere/zotero-pmcid-fetcher#6]
I'm submitted this on recommendation of Zotero forum.  Migrating articles from another library into Zotero, tags are missing.  I've completed the following operation numerous times with no results.  See screenshots attached.

Slide 1 - shows no tags present.
Slide 2 - select all items in folder, right click, select Fetch PMCID keys.  Note - nothing visibly/audibly happens.  No tags appear in Zotero library.
Slide 3 - right click and select Export items.  
Slide 4 - Export items to CSV.
Slide 5 - CSV does not contain PMID/PMCID numbers (zero hits on search results).

Thank you.

[2023-04-26 github fetcher bug.pptx](https://github.com/retorquere/zotero-pmcid-fetcher/files/11335640/2023-04-26.github.fetcher.bug.pptx)

**Comment by retorquere** [comment]
Do all of these items have a DOI?

**Comment by vicdsim** [comment]
Most do have DOI.  See attached.
[2023-04-26 DOI numbers.pptx](https://github.com/retorquere/zotero-pmcid-fetcher/files/11335811/2023-04-26.DOI.numbers.pptx)

**Comment by retorquere** [comment]
Can you select a few of those, export as Zotero RDF, and attach that here (not a screenshot, the RDF file).

**Comment by vicdsim** [comment]
export notes or export files?

**Comment by retorquere** [comment]
Neither

**Comment by vicdsim** [comment]
see attached

**Comment by retorquere** [comment]
Nothing is attached.

**Comment by vicdsim** [comment]
file type not supported.

**Comment by retorquere** [comment]
Zip it, then attach.

**Comment by vicdsim** [comment]
[Exported Items.zip](https://github.com/retorquere/zotero-pmcid-fetcher/files/11335993/Exported.Items.zip)

**Comment by retorquere** [comment]
Please update to 0.0.18 and try again

**Comment by retorquere** [comment]
Does that work?

**Comment by vicdsim** [comment]
Updated to 0.0.18 with some success.  See error messages in slide 1 of attached.  Slides 2-5 are examples of failure to import tags.  Slide 2 specifically is an item with doi, pmid and pmcid which failed.
[2023-05-01 PMCID Error.pptx](https://github.com/retorquere/zotero-pmcid-fetcher/files/11367358/2023-05-01.PMCID.Error.pptx)

**Comment by retorquere** [comment]
Please always attach an zotero RDF export of problematic entries.

**Comment by vicdsim** [comment]
[2023-05-01 Exported Items.zip](https://github.com/retorquere/zotero-pmcid-fetcher/files/11367632/2023-05-01.Exported.Items.zip)

**Comment by retorquere** [comment]
You hit a transient error on the NCBI API. Most items should resolve now. I have put up a new version that will have more readable error messages, you can upgrade in the addons screen.

**Comment by vicdsim** [comment]
I continue to get errors.  Approx 1/3 of the items don't return tags, at least some of which include DOI/PMID/PMCID.  Please see attached.
[2023-05-02 errors.pptx](https://github.com/retorquere/zotero-pmcid-fetcher/files/11377737/2023-05-02.errors.pptx)
[Exported Items (2).zip](https://github.com/retorquere/zotero-pmcid-fetcher/files/11377740/Exported.Items.2.zip)

**Comment by retorquere** [comment]
New version is up, please upgrade. The NCBI API only allows 3 requests per second, so I've spaced them out that way, but one item among the ones in your last post will not resolve because NCBI doesn't know what to do with it: try DOI `10.3109/s10165-008-0045-0` on https://www.ncbi.nlm.nih.gov/pmc/tools/idconv/.

**Comment by retorquere** [comment]
Good?

**Comment by vicdsim** [comment]
Sorry for the delay, I'm back on this project.  Please see attached two DOI errors.
[Exported Items2.zip](https://github.com/retorquere/zotero-pmcid-fetcher/files/11668522/Exported.Items2.zip)

**Comment by retorquere** [comment]
* `Exported Items2.rdf` has DOI `10.1016/S0002-9440(10)64101-6` which the fetcher grabs `PMID: 11290568` and `PMCID: PMC1891908` for without problems
* `10.4049/jimmunol.142.11.3884` does not resolve on https://www.ncbi.nlm.nih.gov/pmc/tools/idconv/. Please test DOIs there before reporting them here.
* The powerpoint shows it cannot resolve `10.3109/s10165-008-0045-0`  which also does not resolve on https://www.ncbi.nlm.nih.gov/pmc/tools/idconv/.

**Comment by vicdsim** [comment]
I'm just a user with no technical or medical library expertise.  Would you kindly explain the ID Converter?  If I understand what you've inferred, if the converter doesn't get a hit on the DOI, then there is nothing further to be done.  What if I get something other than an error message?  In that case I should report to you?

**Comment by retorquere** [comment]
Correct -- if the plugin message says "phrases not found", that's NCBIs way of saying "I don't know this DOI". I'll see if I can make this message more clear.

There's no need to pre-test every DOI, but if you see "phrases not found" (or the better message I may be able to show), you can either trust that or verify at https://www.ncbi.nlm.nih.gov/pmc/tools/idconv/ to see whether that's the case. Any other error you can report here.

**Comment by vicdsim** [comment]
Thanks.  Please see screenshots attached.  When I put the DOI into the converter, it is recognized and associated with PMID/PMCID, but Zotero PMCID Fetcher has not captured tags.  Are these items that you would troubleshoot?  If so, I will continue looking for similar issues and send an RDF export.

[2023-06-07 no tags, no ID converter error.pptx](https://github.com/retorquere/zotero-pmcid-fetcher/files/11680640/2023-06-07.no.tags.no.ID.converter.error.pptx)

**Comment by retorquere** [comment]
Please attach an RDF export of that item -- if I fetch `10.1016/j.jdin.2022.07.006` through the fetcher plugin I get

```
PMID: 36089937
PMCID: PMC9449733
```

as expected.

**Comment by fjavier10** [comment]
Cannot download/install zotero-pmcid-fetcher-0.0.23.xpi, using Firefox 116.0.3 (64-bit) Windows 10 64b education. 
As I click the link a message appears: "github.com. The add-on downloaded from this site could not be installed because it appears to be corrupt". Please, advice.
Javier

**Comment by retorquere** [comment]
Download it by right-clicking and choose save-as, not left-clicking.
