### ISSUE TITLE
Plugin fails to load because of "TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode"

### ISSUE THREAD

**Issue by mkyt** [retorquere/zotero-pmcid-fetcher#7]
I installed zotero-pmcid-fetcher on Zotero 6.0.26 (macOS 13.3.1 , ARM64) but it does not load correctly.
I checked the error console and found "TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode" is raised on `bootstrap.js`, line 384.

<img width="752" alt="Screenshot 2023-05-17 at 14 23 11" src="https://github.com/retorquere/zotero-pmcid-fetcher/assets/354132/59d1e150-dc65-476d-80b2-6cba6cc17d04">

I confirmed that disabling strict mode by removing 'use strict' at the beggining of `bootstrap.js` resolved the issue and the plugin worked as expected.

**Comment by retorquere** [comment]
Thanks -- I've removed strict mode. Strange that this should happen all of a sudden.

**Comment by mkyt** [comment]
I have installed the latest version, `zotero-pmcid-fetcher-0.0.22.xpi`, and have confirmed that it is working as expected!
Thank you very much for the quick update!
