### ISSUE TITLE
medline keywords are also imported - can this be switched off?

### ISSUE THREAD

**Issue by github-martin** [retorquere/zotero-pmcid-fetcher#9]
Thanks for this plugin.
The plugin fetches the PMID but in addition, it also fetches the keywords (MeSH terms) as Zotero tags - can the latter be switched off? I would only need the PMID and and have my own collection of tags.
I have version 0.0.26 installed.
Thank you, 
Martin

**Comment by retorquere** [comment]
With build 22, go into "Preferences" => "Advanced" => "Config Editor", right-click and create a new boolean entry named `extensions.zotero.pmcid.tags` and set it to `false`. If you can test to see if that does what you want, I can fold that into a new release.

**Comment by github-martin** [comment]
??? this is unreal -- coming back from the toilet and the issue is already fixed!!!!
I tested 0.0.26.9.22 according to your instructions and it perfectly does the job.
Thanks a lot!

**Comment by retorquere** [comment]
Super, a new release build is scheduled but it's just 0.0.26.9.22 under a new name. You will be upgraded to that automatically.
